copyright: Copyright &copy; 2020 - 2021 jsyPrajna
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://notes.caijiqhx.top/
    name: cjqxh on github
extra_css:
- static/css/extra.css
- static/css/main.bf3dc0a9.min.css
extra_javascript:
- static/js/bundle.525231ca.min.js
- https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
- static/js/extra.js
- https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
- abbr
- attr_list
- admonition
- md_in_html
- codehilite:
    guess_lang: false
    linenums: true
- def_list
- footnotes
- meta
- toc:
    permalink: '*'
- pymdownx.arithmatex
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
    emoji_index: !!python/name:materialx.emoji.twemoji ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
      name: mermaid
- pymdownx.betterem:
    smart_enable: all
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
nav:
- index.md
- C++:
  - C++/C++ core programming.md
  - C++/C++ improves programming.md
plugins:
- search
- git-revision-date-localized
- minify:
    minify_html: true
repo_name: jsyPrajna/Notes
repo_url: https://github.com/jsyPrajna/Notes
site_author: jsyPrajna
site_description: "\u8FD9\u4E2A\u4EBA\u5F88\u61D2\uFF0C\u4EC0\u4E48\u4E5F\u6CA1\u7559\
  \u4E0B"
site_name: "\u59DC\u67D0\u7684\u7B14\u8BB0"
site_url: https://github.com/jsyPrajna/Notes
theme:
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  - content.code.annotate
  font:
    code: Source Code Pro
    text: Noto Sans
  icon:
    repo: fontawesome/brands/github-alt
  language: zh
  logo: static/big-yellow-star.jpg
  name: material
  palette:
  - accent: red
    primary: teal
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - accent: green
    primary: black
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
