site_name: caijiqhx notes
site_description: caijiqhx notes
site_author: caijiqhx
site_url: https://notes.caijiqhx.top
repo_name: caijiqhx/Notes
repo_url: https://github.com/caijiqhx/Notes
copyright: "Copyright &copy; 2020 - 2021 caijiqhx"
extra_css:
- static/css/extra.css
- static/css/main.bf3dc0a9.min.css
extra_javascript:
- static/js/bundle.525231ca.min.js
- https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
- static/js/extra.js
- https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: teal
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt
  logo: static/githubcat.jpg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
  font:
    text: "Noto Sans"
    code: "Source Code Pro"
plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true  
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - md_in_html
  - codehilite:
      linenums: true
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: "*"
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji ""
      emoji_generator: !!python/name:materialx.emoji.to_svg ""
  - pymdownx.highlight      
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""  
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde